---
output:
  pdf_document: default
  html_document:
    fig_caption: yes
---


```{r}
library(tidyverse)
library(lubridate)
```


```{r}
d_activity <- read.csv("C:/programming languages/R/Casestudy/dailyActivity_merged.csv")
d_calories <- read.csv("C:/programming languages/R/Casestudy/dailyCalories_merged.csv")

d_intensities <- read.csv("C:/programming languages/R/Casestudy/dailyIntensities_merged.csv")

d_steps <- read.csv("C:/programming languages/R/Casestudy/dailySteps_merged.csv")
```

```{r}
glimpse(d_activity) 
glimpse(d_calories) 
glimpse(d_intensities) 
glimpse(d_steps)
```

```{r}
n_distinct(d_activity$Id)

n_distinct(d_calories$Id)

n_distinct(d_intensities$Id)

n_distinct(d_steps$Id)
```

```{r}
sum(duplicated(d_activity))

sum(duplicated(d_calories))

sum(duplicated(d_intensities))

sum(duplicated(d_steps))
```

```{r}
d_sleep <- read.csv("C:/programming languages/R/Casestudy/sleepDay_merged.csv")

h_steps <- read.csv("C:/programming languages/R/Casestudy/hourlySteps_merged.csv")

h_calories <- read.csv("C:/programming languages/R/Casestudy/hourlyCalories_merged.csv")
```


```{r}
glimpse(d_sleep)
glimpse(h_steps)
glimpse(h_calories)
```

```{r}
n_distinct(d_sleep$Id)

n_distinct(h_steps$Id)

n_distinct(h_calories$Id)
```

```{r}
sum(duplicated(d_sleep))

sum(duplicated(h_steps))

sum(duplicated(h_calories))
```

```{r}
d_activity <- d_activity %>% distinct() %>% drop_na()

d_sleep <- d_sleep %>% distinct() %>% drop_na()

h_steps <- h_steps %>% distinct() %>% drop_na()

h_calories <- h_calories %>%  distinct() %>% drop_na()
```

```{r}
d_activity <- rename_with(d_activity,tolower)

d_sleep <- rename_with(d_sleep,tolower)

h_steps <- rename_with(h_steps,tolower)

h_calories <- rename_with(h_calories,tolower)
```

```{r}
d_activity <- d_activity %>% rename(date=activitydate) %>% mutate(date=as_date(date,format="%m/%d/%Y"))

d_sleep <- d_sleep %>% rename(date=sleepday) %>% mutate(date=as_date(date,format="%m/%d/%Y %I:%M:%S %p", tz=Sys.timezone()))

h_steps <- h_steps %>% rename(date=activityhour) %>% mutate(date=as.POSIXct(date,format="%m/%d/%Y %I:%M:%S %p", tz=Sys.timezone()))

h_calories <- h_calories %>% rename(date=activityhour) %>% mutate(date=as.POSIXct(date,format="%m/%d/%Y %I:%M:%S %p", tz=Sys.timezone()))
```

```{r}
d_ac_sleep <- merge(d_activity,d_sleep,by=c("id","date"))

d_use <- d_ac_sleep %>% group_by(id) %>% summarize(days=sum(n())) %>% mutate(use_level=case_when(days>=1 & days<=5 ~ "Low Use", days>=6 & days<=15 ~ "Moderate Use", days>=16 & days<=31 ~ "High Use"))

print(d_use)
```

```{r}
d_use_per <- d_use %>% group_by(use_level) %>% summarize(total=n()) %>% mutate(totals=sum(total)) %>% group_by(use_level) %>% summarize(total_per=total/totals)

print(d_use_per)
```

```{r}
ggplot(data=d_use_per,aes(x="",y=total_per,fill=use_level))+geom_col()+coord_polar(theta="y")+ labs(title = "Use of our product",subtitle ="Low usage should be dealt",x="",y="")
```

```{r}
d_ac_sleep <- d_ac_sleep %>% mutate(weekday=weekdays(date))

d_ac_sleep$weekday <- ordered(d_ac_sleep$weekday, levels=c("Monday","Tuesday","Wednesday","Thursday", "Friday","Saturday","Sunday"))
```

```{r}
d_steps_sleep <- d_ac_sleep %>% group_by(weekday) %>% summarize(weeks_steps=mean(totalsteps),weeks_sleep=mean(totalminutesasleep))
```

```{r}
ggplot(d_steps_sleep)+geom_col(aes(x=weekday,y=weeks_steps,fill=weeks_steps))+ scale_fill_gradient(low="red",high="green")
```

```{r}
ggplot(d_steps_sleep)+geom_col(aes(x=weekday,y=weeks_sleep,fill=weeks_sleep))+ scale_fill_gradient(low="red",high="green")
```

```{r}
h_steps <- h_steps %>% separate(date,into=c("date","time"),sep=" ") %>% mutate(date=ymd(date))

h_calories <- h_calories %>% separate(date,into=c("date","time"),sep=" ") %>% mutate(date=ymd(date))

h_cal_steps <- merge(h_calories,h_steps,by=c("id","date","time"))
```

```{r}
ggplot(h_cal_steps,aes(x=calories,y=steptotal))+geom_point()+geom_smooth()
```
